### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by hazcod** [oblq/i18n#1]
My code:
```
package language

import (
	"github.com/oblq/i18n"
	"golang.org/x/text/language"
	"net/http"
)


var (
	localizer *i18n.I18n
	currentLangTag language.Tag
)

func Init() {
	i18n.New("", &i18n.Config{
		Locales: []string{
			language.English.String(), // "en"
		},
		Locs: map[string]map[string]*i18n.Localization{
			language.English.String(): getEnglishLocs(),
		},
	})
}

func SetLanguage(r *http.Request) {
	currentLangTag = localizer.GetLanguageTag(r)
}

func Translate(msgKey string, parameters interface{}, count int) (string) {
	return localizer.TP(currentLangTag.String(), (count>0), msgKey, parameters)
}
```
Log:
```

mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | INFO 2018/11/08 08:43:02 main.go:58: Started listening on 0.0.0.0:8080
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | TRACE 2018/11/08 08:43:05 router.go:48: GET / 10.255.0.2:36654
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 2018/11/08 08:43:05 http2: panic serving 10.255.0.2:36654: runtime error: invalid memory address or nil pointer dereference
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | goroutine 23 [running]:
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | net/http.(*http2serverConn).runHandler.func1(0xc0000882b8, 0xc00023dfaf, 0xc0001fc000)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/usr/local/go/src/net/http/h2_bundle.go:5870 +0x17c
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | panic(0x7f7320, 0xb96060)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | github.com/oblq/i18n.(*I18n).getLocaleUnsafe(0x0, 0xc000188200, 0x40, 0x3f)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/vendor/github.com/oblq/i18n/locale.go:28 +0x34
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | github.com/oblq/i18n.(*I18n).GetLanguageTag(0x0, 0xc000188200, 0x0, 0x0, 0x0)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/vendor/github.com/oblq/i18n/locale.go:52 +0x4a
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | mini/language.SetLanguage(0xc000188200)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/language/lang.go:27 +0x3b
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | mini/handlers.PanicHandler.func1(0x8dd5c0, 0xc0000882b8, 0xc000188200, 0x7f7320, 0xb96060)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/handlers/panichandler.go:13 +0xdb
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | github.com/julienschmidt/httprouter.(*Router).recv(0xc0000a45c0, 0x8dd5c0, 0xc0000882b8, 0xc000188200)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/vendor/github.com/julienschmidt/httprouter/router.go:270 +0x79
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | panic(0x7f7320, 0xb96060)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | github.com/oblq/i18n.(*I18n).getLocaleUnsafe(0x0, 0xc000188300, 0xc00006d9e0, 0x0)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/vendor/github.com/oblq/i18n/locale.go:28 +0x34
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | github.com/oblq/i18n.(*I18n).GetLanguageTag(0x0, 0xc000188300, 0x0, 0x0, 0x0)
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | 	/src/vendor/github.com/oblq/i18n/locale.go:52 +0x4a
mini_mini.1.gyxaipafwsc1@linuxkit-025000000001    | mini/language.SetLanguage(0xc000188300)

```

**Comment by oblq** [comment]
The error happened on calling localizer.GetLanguageTag(r) with a nil *http.Request, I already fixed that bug but the last 3 commits was not tagged at all, be sure to use the last version, just added a new tag.

**Comment by oblq** [comment]
this is the last version:

`
func (i18n *I18n) getLocaleUnsafe(r *http.Request) (locale string) {
	if r == nil {
		return
	}

	if i18n.GetLocaleOverride != nil {
		locale = i18n.GetLocaleOverride(r)
	}

	if len(locale) == 0 {
		if cookieLang, err := r.Cookie(cookieKey1); err == nil {
			locale = cookieLang.Value
		} else if cookieLang, err := r.Cookie(cookieKey2); err == nil {
			locale = cookieLang.Value
		} else if acceptLang := r.Header.Get(headerKey); len(acceptLang) > 0 {
			locale = acceptLang
		}
	}
	return
}`

**Comment by hazcod** [comment]
In the end the issue seemed to be related to me not initializing localizer, thanks for the swift feedback!
